---
- name: Implementing loops
  hosts: all
  tasks:
   - name: Installing s/w packages
     apt:
      name: "{{item}}"
      state: present
      update_cache: no
     with_items:
      - tree
      - git
      - maven
      - firewalld
...
