---
- name: create a user and copy /etc/passwd file
  hosts: all
  tasks:
   - name: create a user
     user:
      name: Anu
      password: anu
      uid: 1357
      home: /home/Anu
      shell: /bin/bash
   - name: copy /etc/passwd file
     copy:
      src: /etc/passwd
      dest: /home/Anu

...
