---
- name: Create multiple users and copy files into their home directories
  hosts: all
  tasks: 
   - name: Create multiple users
     user:
      name: "{{item.a}}"
      password: "{{item.b}}"
      uid: "{{item.c}}"
      home: "{{item.d}}"
     with_items:
      - {a: Siva,b: siva,c: 1003,d: /home/ubuntu/Siva}
      - {a: Malli,b: malli,c: 1002,d: /home/Malli}
   - name: Copy password file and group file
     copy:
      src: "{{item.a}}"
      dest: "{{item.b}}"
     with_items:
      - {a: /etc/passwd,b: /home/ubuntu/Siva}
      - {a: /etc/group,b: /home/Malli}

...
