---
- name: Performing CI-CD
  hosts: devserver
  tasks:
   - name: Install required s/w
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: openjdk-8-jdk,b: yes}
      - {a: git,b: no}
      - {a: maven,b: no}
   - name: Download code from git
     git:
      repo: https://github.com/vaishnavi972/maven.git
      dest: /home/ubuntu/dev
   - name: Build the code
     shell: cd /home/ubuntu/dev;mvn package
   - name: Fetch the artifact from devserver to controller
     fetch:
      src: /home/ubuntu/dev/webapp/target/webapp.war
      dest: /tmp
- name: Install tomcat8 & tomcat8-admin on qaserver and prodserver
  hosts: servers
  tasks:
   - name: Install required s/w
     apt:
      name: "{{item}}"
      state: present
     with_items:
      - tomcat8
      - tomcat8-admin
      - git
      - openjdk-8-jdk
- name: Copy artifact into tomcat on qaserver and run the selenium test scripts
  hosts: qaserver
  tasks:
   - name: Copy artifact from controller to qaserver
     copy:
      src: /tmp/172.31.16.84/home/ubuntu/dev/webapp/target/webapp.war
      dest: /var/lib/tomcat8/webapps/qaenv.war
   - name: Download the selenium scripts
     git:
      repo: https://github.com/vaishnavi972/FunctionalTesting.git
      dest: /home/ubuntu/qa
   - name: Execute the selenium scripts
     shell: java -jar /home/ubuntu/qa/testing.jar
- name: Deploy artifact into tomcat on prodserver
  hosts: prodserver
  tasks:
   - name: Copy artifact into prodserver
     copy:
      src: /tmp/172.31.16.84/home/ubuntu/dev/webapp/target/webapp.war
      dest: /var/lib/tomcat8/webapps/prodenv.war
...
