---
- name: Installing S/w using playscope variable
  hosts: all
  vars:
   - a: tomcat8
   - b: present
   - c: yes
  tasks:
   - name: Install / uninstall s/w packages
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...
