---
- name: Implementing loops
  hosts: all
  tasks:
   - name: Installing s/w packages
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
     - {a: tree,b: present,c: no}
     - {a: git,b: present,c: no}
     - {a: maven,b: latest,c: yes}
     - {a: firewalld,b: absent,c: no}

...
